
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ParserLexer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMPARACION = 6;
  public static final int INTEGER_T = 2;
  public static final int SUMA = 7;
  public static final int CHAR_T = 4;
  public static final int L_STRING = 11;
  public static final int EOF = 0;
  public static final int FINLINEA = 8;
  public static final int error = 1;
  public static final int L_INTEGER = 10;
  public static final int STRING_T = 3;
  public static final int IDENTIFICADOR = 9;
  public static final int ASIGNA = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INTEGER_T",
  "STRING_T",
  "CHAR_T",
  "ASIGNA",
  "COMPARACION",
  "SUMA",
  "FINLINEA",
  "IDENTIFICADOR",
  "L_INTEGER",
  "L_STRING"
  };
}

